simulate: False

Rbin: R
STAR: STAR
featureCounts: featureCounts
bedtools: bedtools
bedGraphToBigWig: bedGraphToBigWig
faSize: faSize

## run limits
nthreads: 8
per_task_max_nthreads: 4
per_task_max_mem:  103882211200 # not used anymore
max_mem_mb: 350000 ## these are megabytes

rock_method_path: "."

working_dir: /storage2/fs1/dspencer/Active/spencerlab/projects/gata2_regulation/hsc_bd_rhapsody/rock_roi_method/BD_ROCKANDROI_GATA2_260416_RO04050/

gtf: Ensemble105_GATA2_tso_targets_260416.gtf
genome: /storage2/fs1/dspencer/Active/spencerlab/refdata/hg38/sequence/hg38_mgi_patch.fa

# i.e. cDNA read length minus 1
sjdbOverhang: 150

## run mode, one of these (please see the README / docs):
##   'tso off- and ontarget unique'
##   'tso ontarget_multi'
##   'all'
run_mode: 'all' #tso off- and ontarget unique'

## GTF `source` field identifying on-target rock- or roi- features
capture_gtf_column_2_pattern : 'captured'
featurecounts_t: 'exon' ## feature counting unit for featurecounts
featurecounts_g: 'gene_id' ## feature grouping unit for featurecounts

## multimodal means they sequenced tso+wta; unimodal that only sequenced wta
samples:
  - name: RO04050_WTA
    uses:
      cb_umi_fq: /storage2/fs1/dspencer/Active/spencerlab/data/work_orders/20260713_SR012021_rhapsody/fastq/LIB155776_23WJJKLT4_S1_L002_R1_001.fastq.gz
      cdna_fq: /storage2/fs1/dspencer/Active/spencerlab/data/work_orders/20260713_SR012021_rhapsody/fastq/LIB155776_23WJJKLT4_S1_L002_R2_001.fastq.gz
      expected_cells: 40000
      whitelist: 384x3
  - name: RO04050_GATA2_2604216
    uses:
      cb_umi_fq: /storage2/fs1/dspencer/Active/spencerlab/data/work_orders/20260713_SR012021_rhapsody/fastq/LIB155777_23WJJKLT4_S2_L002_R1_001.fastq.gz
      cdna_fq: /storage2/fs1/dspencer/Active/spencerlab/data/work_orders/20260713_SR012021_rhapsody/fastq/LIB155777_23WJJKLT4_S2_L002_R2_001.fastq.gz
      expected_cells: 40000
      whitelist: 384x3
